name: HMM Daily Alert

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install yfinance hmmlearn pandas numpy scikit-learn ta feedparser nltk beautifulsoup4 requests joblib matplotlib google-cloud-storage

      - name: Download NLTK data
        run: |
          python - <<EOF
          import nltk
          nltk.download('vader_lexicon')
          EOF

      # Export GCP Service Account JSON (use printf, not echo!)
      - name: Export GCP Service Account JSON
        run: |
          printf '%s' "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" > /tmp/gcp-key.json
        shell: bash

      # Validate the GCP JSON
      - name: Validate GCP JSON (safe)
        run: |
          python -c "import json; json.load(open('/tmp/gcp-key.json'))" && echo 'GCP JSON is valid'


      - name: Run bot
        run: python HMM_Strategy_v12_MultiAsset_withSpotGoldAlertsFull.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
