name: HMM Daily Alert

on:
  schedule:
    # Runs every 15 min for testing; change to '0 0 * * *' for 8am SGT only
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install yfinance hmmlearn pandas numpy scikit-learn ta feedparser nltk beautifulsoup4 requests joblib matplotlib google-cloud-storage

      - name: Download NLTK data
        run: |
          python - <<EOF
          import nltk
          nltk.download('vader_lexicon')
          EOF

      # Write GCP Service Account Key to file
      - name: Write GCP Service Account Key to file
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" > gcp-key.json

      - name: Run bot
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/gcp-key.json"
          python HMM_Strategy_v12_MultiAsset_withSpotGoldAlertsFull.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
