name: HMM Daily Alert

on:
  schedule:
    # for testing: every 15m → change to '0 0 * * *' for once per day at 00:00 UTC (08:00 SGT)
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            yfinance \
            hmmlearn \
            pandas \
            numpy \
            scikit-learn \
            ta \
            feedparser \
            nltk \
            beautifulsoup4 \
            requests \
            joblib \
            matplotlib \
            google-cloud-storage
        shell: bash

      - name: Download NLTK data
        run: |
          python - <<EOF
          import nltk
          nltk.download('vader_lexicon')
          EOF
        shell: bash

      - name: Export GCP Service Account JSON
        run: |
          printf '%s' "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" > /tmp/gcp-key.json
        shell: bash

      - name: "DEBUG: show first 2 lines of /tmp/gcp-key.json"
        run: |
          echo "---- FIRST 2 LINES OF /tmp/gcp-key.json ----"
          head -n 2 /tmp/gcp-key.json
          echo "--------------------------------------------"
        shell: bash

      - name: Run bot
        run: python HMM_Strategy_v12_MultiAsset_withSpotGoldAlertsFull.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        shell: bash
