name: HMM Daily Alert

on:
  schedule:
    # change to '0 0 * * *' for 8 AM SGT daily once you’re done testing
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install \
            yfinance hmmlearn pandas numpy scikit-learn ta \
            feedparser nltk beautifulsoup4 requests joblib \
            matplotlib google-cloud-storage

      - name: Download NLTK data
        run: |
          python - <<EOF
          import nltk
          nltk.download('vader_lexicon')
          EOF
        shell: bash

      - name: Export GCP Service Account JSON
        shell: bash
        run: |
          # Convert literal "\n" in your secret into real newlines:
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" \
            | sed 's|\\n|\n|g' \
            > /tmp/gcp-key.json

      - name: Print first line of GCP JSON (debug only)
        shell: bash
        run: |
          echo "----FIRST LINE----"
          head -n 1 /tmp/gcp-key.json || echo "(file missing)"
          echo "----END FIRST LINE----"

      - name: Validate GCP JSON
        shell: bash
        run: |
          python - <<EOF
          import json
          json.load(open('/tmp/gcp-key.json'))
          print("✅ GCP JSON is valid")
          EOF

      - name: Run bot
        shell: bash
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID:   ${{ secrets.CHAT_ID }}
          # point Google client library at our reconstructed file:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        run: |
          python HMM_Strategy_v12_MultiAsset_withSpotGoldAlertsFull.py
