name: HMM Daily Alert

on:
  schedule:
    - cron: '0 21 * * 1-5'  # 05:00 SGT weekdays
  workflow_dispatch:

jobs:
  run-alert:
    runs-on: [ubuntu-latest, self-hosted]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install TA-Lib dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
          tar -xvzf ta-lib-0.4.0-src.tar.gz
          cd ta-lib/
          ./configure --prefix=/usr
          make
          sudo make install
        if: runner.os == 'Linux'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download NLTK data
        run: python -c "import nltk; nltk.download('vader_lexicon')"

      - name: Export GCP Service Account JSON
        run: |
          echo "${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}" \
            | base64 --decode > /tmp/gcp-key.json

      - name: Run bot
        run: python HMM_Strategy_v14_Enhanced_Profitability.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json

