name: Run HMM Strategy v12a

on:
  workflow_dispatch: 
  push:  
    branches:
      - hmm-v12a-per-asset-scaling

jobs:
  run-v12a:
    runs-on:ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python HMM_Strategy_v12a_MultiAsset_PerAssetScaler.py
