name: Run HMM Strategy v12b

on:
  workflow_dispatch:
  push:
    branches:
      - hmm-v12b-per-asset-bic

jobs:
  run-hmm-v12b:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install yfinance hmmlearn scikit-learn matplotlib pandas

    - name: Run HMM Strategy v12b
      run: python HMM_Strategy_v12b_MultiAsset_PerAssetScaler_BIC.py
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
